/*
  Venue data for Peach Hour — researched from the web on 2026-10-01.

  hhStatus:
    "confirmed" – from the venue's own site, or an official/editorial guide from 2026
                  (Virginia-Highland District, Aug 2026; The Infatuation, Aug 24 2026;
                  Atlanta BeltLine blog, Apr 7 2026)
    "reported"  – from third-party listings that may be stale; double-check
    "unknown"   – venue mentions happy hour (or might have one) but no times found

  Price level ($–$$$) and vibes are editorial estimates. Map coordinates were geocoded on
  2026-10-02 (OpenStreetMap business/address data, US Census geocoder as fallback).
  outdoor: "Patio" | "Rooftop" | "Porch" — best-effort from venue sites/photos/reviews.
  deals: any of "beer", "wine", "cocktails", "food", "oysters".
  hours: index 0=Sun … 6=Sat, each [open, close], a list of [open, close] ranges (e.g. lunch +
  dinner), or null if closed; whole field null if unknown. Partly sourced from OpenStreetMap.
  website: official site (linked from the name). zip: ZIP code, searchable.
  beltline: walk time to the nearest Atlanta BeltLine trail (only for spots within ~300 m),
  measured against OpenStreetMap trail data on 2026-10-05; these spots also get the "Beltline access" vibe.
  Happy-hour windows: { days, start, end, note? }. "24:00" start = midnight that night.
  allDay: true = a day-long special (still only counts while the venue is open).
  end: "close" = runs until that day's closing time (needs hours).
*/
(function () {
  const WEEKDAYS = [1, 2, 3, 4, 5];
  const CHECKED = "2026-10-01";
  const S = {
    cs: { label: "Colony Square specials", url: "https://colonysquare.com/restaurant-specials/" },
    ramb: { label: "Rambler Atlanta (2025)", url: "https://rambleratlanta.com/resources/happy-hour-near-georgia-tech/" },
    vhd: { label: "Virginia-Highland District guide (Aug 2026)", url: "https://www.virginiahighlanddistrict.com/guides/happy-hours" },
    inf: { label: "The Infatuation (Aug 2026)", url: "https://www.theinfatuation.com/atlanta/guides/the-best-happy-hours-in-atlanta" },
    bl: { label: "Atlanta BeltLine blog (Apr 2026)", url: "https://beltline.org/blog/where-to-end-your-workday-on-the-beltline/" },
  };
  const days = spec => [0, 1, 2, 3, 4, 5, 6].map(d => (spec[d] === undefined ? null : spec[d]));

  window.VENUES = [
    // ── Virginia-Highland ─────────────────────────────────────────
    { id: "whiskey-bird", name: "Whiskey Bird", neighborhood: "Virginia-Highland",
      address: "1409 N Highland Ave NE", lat: 33.79269, lng: -84.35178, price: 2, type: "Restaurant",
      website: "http://eatwhiskeybird.com", zip: "30306",
      cuisine: ["Asian"], vibes: ["Date night"], outdoor: [], hours: days({ 0: ["10:30", "20:00"], 2: ["16:00", "21:00"], 3: ["16:00", "21:00"], 4: ["16:00", "21:00"], 5: ["10:30", "21:30"], 6: ["10:30", "21:30"] }),
      happyHours: [{ days: [3, 4], start: "16:00", end: "18:30" }, { days: [5, 6, 0], start: "15:00", end: "18:00" }],
      deals: ["cocktails", "wine", "beer", "food"], dealText: "$10 cocktails (hibiscus margarita, Lo-Fi spritz, Thai 75) & rosé · $10 22oz Sapporo · bites $6–10 like yakitori & spicy tuna nachos",
      hhStatus: "confirmed", sources: [{ label: "Whiskey Bird happy hour menu", url: "http://eatwhiskeybird.com" }, S.vhd] },

    { id: "family-dog", name: "The Family Dog", neighborhood: "Virginia-Highland",
      address: "1402 N Highland Ave NE", lat: 33.79278, lng: -84.35251, price: 1, type: "Bar",
      website: "https://www.thefamilydogatl.com/", zip: "30306",
      cuisine: ["Bar food"], vibes: ["Sports"], outdoor: ["Patio"],
      hours: days({ 0: ["11:00", "21:30"], 2: ["16:00", "22:30"], 3: ["16:00", "22:30"], 4: ["16:00", "22:30"], 5: ["12:00", "00:30"], 6: ["11:00", "00:30"] }),
      happyHours: [{ days: [2, 3, 4, 5], start: "16:00", end: "19:00" }],
      deals: ["beer", "cocktails"], dealText: "$4 Montucky & Tecate · $6 margaritas & mules",
      hhStatus: "confirmed", sources: [S.vhd] },

    { id: "ela", name: "Ela", neighborhood: "Virginia-Highland",
      address: "1186 N Highland Ave NE", lat: 33.78687, lng: -84.35546, price: 2, type: "Restaurant",
      website: "https://ela-atlanta.com/", zip: "30306",
      cuisine: ["Mediterranean"], vibes: ["Date night"], outdoor: ["Patio"], hours: days({ 0: ["11:00", "21:00"], 1: ["16:00", "21:30"], 2: ["16:00", "21:30"], 3: ["16:00", "21:30"], 4: ["16:00", "21:30"], 5: ["16:00", "22:00"], 6: ["11:00", "22:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }, { days: [6, 0], start: "15:00", end: "17:00" }],
      deals: ["wine", "cocktails", "beer", "food"],
      dealText: "$8 cocktails · $6 wine · $4 lager · $8 cauliflower falafel · $9 Moroccan hot chicken · mezze from $7",
      hhStatus: "confirmed", sources: [{ label: "Ela happy hour menu", url: "https://www.ela-atlanta.com/menus" }, S.vhd, S.inf] },

    { id: "bar-bacoa", name: "Bar.bacoa", neighborhood: "Virginia-Highland",
      address: "1000 Virginia Ave NE", lat: 33.78251, lng: -84.35468, price: 2, type: "Restaurant",
      website: "https://barbacoaatl.com/",
      zip: "30306",
      cuisine: ["Mexican / Tacos", "Spanish / Tapas"], vibes: ["Groups"], outdoor: ["Patio"],
      hours: days({ 0: ["12:00", "21:00"], 1: ["16:00", "22:00"], 2: ["16:00", "22:00"], 3: ["16:00", "22:00"], 4: ["16:00", "22:00"], 5: ["16:00", "22:00"], 6: ["12:00", "22:00"] }),
      happyHours: [
        { days: [1], start: "16:00", end: "22:00", note: "$6 house margaritas" },
        { days: [2], start: "16:00", end: "22:00", note: "Half-price tacos" },
        { days: [3], start: "16:00", end: "22:00", note: "$30 select wine bottles" },
      ],
      deals: ["cocktails", "food", "wine"], dealText: "Mon margs · Tue tacos · Wed wine bottles",
      hhStatus: "confirmed", sources: [S.vhd] },

    { id: "murphys", name: "Murphy's", neighborhood: "Virginia-Highland",
      address: "997 Virginia Ave NE", lat: 33.78206, lng: -84.35488, price: 2, type: "Restaurant",
      website: "https://www.murphysatlanta.com/", zip: "30306",
      cuisine: ["American", "Brunch"], vibes: ["Date night"], outdoor: [], hours: days({ 0: ["09:00", "21:00"], 1: ["11:00", "21:00"], 2: ["11:00", "21:00"], 3: ["11:00", "21:00"], 4: ["11:00", "21:00"], 5: ["11:00", "22:00"], 6: ["09:00", "22:00"] }),
      happyHours: [{ days: [4], start: "16:00", end: "20:00", note: "Wine Shop happy hour" }],
      deals: ["wine", "food"], dealText: "Wine Shop flight: four wines + seasonal charcuterie for $20 · Extra wine pours $8",
      hhStatus: "confirmed", sources: [S.vhd, { label: "murphysatlanta.com", url: "https://www.murphysatlanta.com/events/wine-shop-happy-hour" }] },

    { id: "moes-joes", name: "Moe's & Joe's", neighborhood: "Virginia-Highland",
      address: "1033 N Highland Ave NE", lat: 33.78282, lng: -84.35418, price: 1, type: "Dive bar",
      website: "https://www.moesandjoesatl.com/", zip: "30306",
      cuisine: ["Bar food"], vibes: ["Sports", "Late night"], outdoor: ["Patio"], hours: days({ 0: ["12:00", "24:00"], 1: ["11:30", "01:00"], 2: ["11:30", "02:00"], 3: ["11:30", "02:00"], 4: ["11:30", "02:00"], 5: ["11:30", "02:00"], 6: ["11:30", "02:00"] }),
      happyHours: [
        { days: [0], allDay: true, note: "$5 PBR pitchers" },
        { days: [2], allDay: true, note: "$3.50 PBR pitchers" },
        { days: [3], allDay: true, note: "$2 PBR tallboys + trivia" },
        { days: [4], allDay: true, note: "$5 rotating pitcher" },
      ],
      deals: ["beer"], dealText: "Daily PBR specials, not a fixed happy-hour window",
      hhStatus: "confirmed", sources: [S.vhd] },

    { id: "fontaines", name: "Fontaine's Oyster House", neighborhood: "Virginia-Highland",
      address: "1026½ N Highland Ave NE", lat: 33.78284, lng: -84.35454, price: 2, type: "Bar",
      zip: "30306",
      cuisine: ["Seafood"], vibes: ["Late night"], outdoor: [],
      hours: days({ 0: ["11:30", "22:00"], 1: ["11:30", "22:00"], 2: ["16:00", "22:00"], 3: ["11:30", "22:00"], 4: ["11:30", "22:00"], 5: ["11:30", "00:00"], 6: ["11:30", "00:00"] }),
      happyHours: [{ days: [2], allDay: true, note: "$15 house raw dozen oysters" }],
      deals: ["oysters", "food"], dealText: "Tuesday: $15 dozen raw oysters on the half shell",
      hhStatus: "confirmed", sources: [S.vhd] },

    { id: "truva", name: "Truva Turkish Kitchen", neighborhood: "Virginia-Highland",
      address: "842 N Highland Ave NE", lat: 33.77747, lng: -84.35274, price: 2, type: "Restaurant",
      website: "https://www.truvahighland.com/",
      zip: "30306",
      cuisine: ["Mediterranean"], vibes: [], outdoor: ["Patio"], hours: days({ 0: ["10:00", "22:00"], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["11:00", "23:00"], 6: ["10:00", "23:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "15:00", end: "18:00" }],
      deals: [], dealText: "Weekday happy hour (specific deals not listed)",
      hhStatus: "confirmed", sources: [S.vhd] },

    { id: "atkins-park", name: "Atkins Park", neighborhood: "Virginia-Highland",
      address: "794 N Highland Ave NE", lat: 33.77614, lng: -84.35268, price: 2, type: "Bar",
      website: "https://www.atkinspark.com/", zip: "30306",
      cuisine: ["American", "Southern"], vibes: ["Late night", "Sports"], outdoor: [], hours: days({ 0: ["12:00", "24:00"], 2: ["16:00", "24:00"], 3: ["16:00", "24:00"], 4: ["16:00", "01:00"], 5: ["12:00", "03:00"], 6: ["12:00", "03:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "15:00", end: "18:00" }, { days: [5], start: "18:00", end: "18:15", note: "Free \"Six O'Clock Shot\" round" }],
      deals: ["beer", "cocktails"], dealText: "$5 wells & drafts · Fridays: complimentary 6PM shot",
      hhStatus: "reported", sources: [S.vhd, { label: "atkinspark.com", url: "https://www.atkinspark.com/" }] },

    { id: "highland-tap", name: "Highland Tap", neighborhood: "Virginia-Highland",
      address: "1026 N Highland Ave NE", lat: 33.78263, lng: -84.35460, price: 3, type: "Bar",
      zip: "30306",
      cuisine: ["Steakhouse", "American"], vibes: ["Date night", "Live music"], outdoor: [], hours: null,
      happyHours: [], deals: ["food"], dealText: "Nightly specials (e.g. half-price burgers some nights) — ask the bar",
      hhStatus: "unknown", sources: [S.vhd] },

    { id: "dark-horse", name: "Dark Horse Tavern", neighborhood: "Virginia-Highland",
      address: "816 N Highland Ave NE", lat: 33.77682, lng: -84.35266, price: 1, type: "Bar",
      website: "https://darkhorseatlanta.com/", zip: "30306",
      cuisine: ["Bar food"], vibes: ["Live music", "Late night"], outdoor: [],
      hours: days({ 3: ["18:30", "01:30"], 4: ["18:30", "02:00"], 5: ["20:00", "03:00"], 6: ["20:00", "03:00"] }),
      happyHours: [], deals: [], dealText: "Live band karaoke; no current happy hour found",
      hhStatus: "unknown", sources: [{ label: "darkhorseatlanta.com", url: "https://darkhorseatlanta.com/" }] },

    { id: "dads", name: "Dad's", neighborhood: "Virginia-Highland",
      address: "870 N Highland Ave NE", lat: 33.77832, lng: -84.35308, price: 2, type: "Bar",
      website: "https://www.instagram.com/dadsatl/", zip: "30306",
      cuisine: ["Bar food"], vibes: ["Late night", "Groups"], outdoor: [], hours: null,
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "17:00", end: "19:00" }],
      deals: ["cocktails", "beer", "wine", "food"], dealText: "Dad's Classics: $10 daiquiris, mules, martinis & Manhattans · $4 Narragansett · $5 snaquiris · $8 pinot grigio · $8 pizza rolls & disco fries, $5 Uncrustables",
      hhStatus: "confirmed", sources: [{ label: "@dadsatl on Instagram", url: "https://www.instagram.com/dadsatl/" }] },

    // ── Poncey-Highland ───────────────────────────────────────────
    { id: "tio-luchos", name: "Tio Lucho's", neighborhood: "Poncey-Highland",
      address: "675 N Highland Ave NE", lat: 33.77304, lng: -84.35239, price: 2, type: "Restaurant",
      website: "https://www.tioluchos.com/", zip: "30306",
      cuisine: ["Peruvian", "Seafood"], vibes: ["Date night"], outdoor: [], hours: days({ 0: [["11:30", "15:00"], ["16:00", "21:00"]], 2: ["16:00", "22:00"], 3: ["16:00", "22:00"], 4: [["11:30", "15:00"], ["16:00", "22:00"]], 5: [["11:30", "15:00"], ["16:00", "22:00"]], 6: [["11:30", "15:00"], ["16:00", "22:00"]] }),
      happyHours: [{ days: [2, 3, 4, 5], start: "16:00", end: "18:00" }, { days: [2, 3, 4, 5], start: "21:00", end: "22:00", note: "Low Tide Last Hour" }],
      deals: ["oysters", "cocktails", "food"], dealText: "$1 oysters · $6 margaritas",
      hhStatus: "confirmed", sources: [{ label: "tioluchos.com", url: "https://www.tioluchos.com/" }, S.inf] },

    { id: "manuels", name: "Manuel's Tavern", neighborhood: "Poncey-Highland",
      address: "602 N Highland Ave NE", lat: 33.77077, lng: -84.35272, price: 1, type: "Bar",
      website: "https://manuelstavern.com/", zip: "30307",
      cuisine: ["Bar food", "American"], vibes: ["Sports", "Groups"], outdoor: [],
      hours: days({ 0: ["09:30", "00:00"], 1: ["11:00", "00:00"], 2: ["11:00", "00:00"], 3: ["11:00", "00:00"], 4: ["11:00", "00:00"], 5: ["11:00", "01:00"], 6: ["09:30", "01:00"] }),
      happyHours: [], deals: [], dealText: "Listed as having a happy hour, but times weren't published online",
      hhStatus: "unknown", sources: [{ label: "manuelstavern.com", url: "https://manuelstavern.com/" }] },

    // ── Inman Park ────────────────────────────────────────────────
    { id: "north-highland-pub", name: "The North Highland Pub", neighborhood: "Inman Park",
      address: "469 N Highland Ave NE", lat: 33.76678, lng: -84.35296, price: 1, type: "Pub",
      website: "https://northhighlandpub.com/", zip: "30307",
      cuisine: ["Bar food", "American"], vibes: ["Sports", "Groups", "Late night"], outdoor: [],
      hours: days({ 0: ["11:00", "00:00"], 1: ["11:00", "02:00"], 2: ["11:00", "02:00"], 3: ["11:00", "02:00"], 4: ["11:00", "02:00"], 5: ["11:00", "02:00"], 6: ["11:00", "02:00"] }),
      happyHours: [
        { days: [1], allDay: true, note: "$7 mules" },
        { days: [2], start: "16:00", end: "23:00", note: "$3 tacos & $4.50 margaritas" },
        { days: [3], allDay: true, note: "Half-price select wine bottles" },
        { days: [4], allDay: true, note: "$10 Printer's Ale pitchers" },
        { days: [5], allDay: true, note: "$6 featured draft cocktails" },
        { days: [6], allDay: true, note: "$13.95 domestic buckets" },
        { days: [0], allDay: true, note: "$4 Bloody Marys & mimosas" },
      ],
      deals: ["cocktails", "beer", "wine", "food"], dealText: "Mon: $7 mules · Tue 4–11PM: $3 tacos & $4.50 El Jimador margaritas (dine-in only) · Wed: half-price bottles of select wines · Thu: $10 pitchers of Printer's Ale Dylux · Fri: $6 featured draft cocktails · Sat: $13.95 buckets of Bud Light, Miller Lite or Coors Light · Sun: $4 Bloody Marys & mimosas",
      hhStatus: "confirmed", sources: [{ label: "In-store menu (photo, Oct 2026)", url: "https://northhighlandpub.com/" }, { label: "northhighlandpub.com (Pitcher Thursdays)", url: "https://northhighlandpub.com/" }] },

    { id: "barcelona", name: "Barcelona Wine Bar", neighborhood: "Inman Park",
      address: "240 N Highland Ave NE", lat: 33.76254, lng: -84.35945, price: 2, type: "Wine bar",
      website: "https://barcelonawinebar.com/location/inmanpark/", zip: "30307",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Spanish / Tapas"], vibes: ["Date night", "Beltline access"], outdoor: ["Patio"],
      hours: days({ 0: ["11:30", "00:00"], 1: ["16:00", "00:00"], 2: ["16:00", "00:00"], 3: ["16:00", "00:00"], 4: ["13:00", "00:00"], 5: ["13:00", "00:00"], 6: ["11:30", "00:00"] }),
      happyHours: [{ days: [1, 2, 3, 4], start: "16:00", end: "18:00" }, { days: [5], start: "13:00", end: "18:00" }, { days: [1], start: "18:00", end: "24:00", note: "Half-off bottles (from 4PM)" }],
      deals: ["wine", "food"], dealText: "Happy hour menu · Mondays: half-off bottles 4PM–midnight",
      hhStatus: "confirmed", sources: [{ label: "barcelonawinebar.com", url: "https://barcelonawinebar.com/location/inmanpark/" }] },

    { id: "beetlecat", name: "BeetleCat", neighborhood: "Inman Park",
      address: "299 N Highland Ave NE", lat: 33.76245, lng: -84.35858, price: 3, type: "Restaurant",
      website: "https://www.beetlecatatl.com/", zip: "30307",
      beltline: { min: 2, trail: "Eastside Trail" },
      cuisine: ["Seafood"], vibes: ["Date night", "Beltline access"], outdoor: ["Patio"], hours: days({ 0: ["10:00", "21:00"], 1: ["16:00", "22:00"], 2: ["16:00", "22:00"], 3: ["16:00", "22:00"], 4: ["16:00", "22:00"], 5: ["16:00", "23:00"], 6: ["10:00", "23:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["oysters", "food", "cocktails"], dealText: "Oyster deals · $10 oyster martini",
      hhStatus: "confirmed", sources: [S.inf] },

    { id: "little-spirit", name: "Little Spirit", neighborhood: "Inman Park",
      address: "299 N Highland Ave NE, Ste R3", lat: 33.76255, lng: -84.35865, price: 2, type: "Cocktail bar",
      website: "https://littlespiritatl.com/", zip: "30307",
      beltline: { min: 2, trail: "Eastside Trail" },
      cuisine: [], vibes: ["Late night", "Date night", "Beltline access"], outdoor: [],
      hours: days({ 1: ["17:30", "02:00"], 2: ["17:30", "02:00"], 3: ["17:30", "02:00"], 4: ["17:30", "02:00"], 5: ["17:30", "02:00"], 6: ["17:30", "02:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "17:30", end: "20:00" }, { days: [1, 2, 3, 4, 5, 6], start: "24:00", end: "02:00", note: "Late-night happy hour" }],
      deals: ["cocktails", "beer", "food"], dealText: "$10 hot dogs till 8PM · $10 espresso martinis, 50/50s, vespers & dirty martinis till 8PM · $8 prosecco & $4 Bibo pilsner till 8PM · Midnight–last call: $9 amaro & 50/50 shots, $10 hot dogs",
      hhStatus: "confirmed", sources: [{ label: "littlespiritatl.com", url: "https://littlespiritatl.com/" }, S.inf] },

    { id: "bartaco-ip", name: "bartaco Inman Park", neighborhood: "Inman Park",
      address: "299 N Highland Ave NE", lat: 33.76235, lng: -84.35865, price: 2, type: "Restaurant",
      website: "https://bartaco.com/location/atlanta-inman/", zip: "30307",
      beltline: { min: 2, trail: "Eastside Trail" },
      cuisine: ["Mexican / Tacos"], vibes: ["Groups", "Beltline access"], outdoor: ["Patio"], hours: null,
      happyHours: [{ days: [1, 2, 3, 4], start: "15:00", end: "18:00" }],
      deals: ["cocktails", "food"], dealText: "\"High tide hour\" at the bar, plus the last 1.5 hrs before close Mon–Thu",
      hhStatus: "confirmed", sources: [{ label: "bartaco.com", url: "https://bartaco.com/location/atlanta-inman/" }] },

    { id: "wrecking-bar", name: "Wrecking Bar Brewpub", neighborhood: "Inman Park",
      address: "292 Moreland Ave NE", lat: 33.76231, lng: -84.34964, price: 2, type: "Brewery",
      website: "https://www.wreckingbarbrewpub.com/", zip: "30307",
      cuisine: ["American", "Bar food"], vibes: ["Cozy"], outdoor: ["Patio"],
      hours: days({ 0: ["11:00", "22:00"], 1: ["16:00", "23:00"], 2: ["16:00", "23:00"], 3: ["16:00", "23:00"], 4: ["16:00", "23:00"], 5: ["12:00", "00:00"], 6: ["12:00", "00:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["beer"], dealText: "Weekday happy hour (deal details not confirmed)",
      hhStatus: "reported", sources: [{ label: "TotalHappyHour", url: "https://www.totalhappyhour.com/happy-hour-for-wrecking-bar-brewpub-in-atlanta-ga-30307/" }] },

    { id: "victory", name: "Victory Sandwich Bar", neighborhood: "Inman Park",
      address: "913 Bernina Ave NE", lat: 33.76400, lng: -84.35779, price: 1, type: "Bar",
      website: "https://www.vicsandwich.com/", zip: "30307",
      beltline: { min: 2, trail: "Eastside Trail" },
      cuisine: ["Sandwiches"], vibes: ["Late night", "Groups", "Beltline access"], outdoor: ["Patio"],
      hours: [0, 1, 2, 3, 4, 5, 6].map(() => ["11:00", "00:00"]),
      happyHours: [], deals: [], dealText: "Cheap drinks all day; no set happy hour found",
      hhStatus: "unknown", sources: [{ label: "vicsandwich.com", url: "https://www.vicsandwich.com/info" }] },

    // ── Eastside Beltline (O4W / Krog St / Ponce City) ────────────
    { id: "eclipse-di-luna", name: "Eclipse di Luna", neighborhood: "Eastside Beltline",
      address: "661 Auburn Ave NE", lat: 33.75612, lng: -84.36543, price: 2, type: "Restaurant",
      website: "https://www.eclipsediluna.com/", zip: "30312",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Spanish / Tapas"], vibes: ["Beltline access", "Groups"], outdoor: [], hours: days({ 0: ["11:00", "22:00"], 1: ["16:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "23:00"], 5: ["11:00", "00:30"], 6: ["11:00", "00:30"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["food", "cocktails", "beer"], dealText: "$7 tapas · $6 cocktails · $3 beer",
      hhStatus: "confirmed", sources: [S.inf, S.bl] },

    { id: "communidad", name: "Communidad Taqueria", neighborhood: "Eastside Beltline",
      address: "655 Highland Ave NE", lat: 33.76087, lng: -84.36586, price: 1, type: "Restaurant",
      website: "https://communidadatl.com/", zip: "30312",
      beltline: { min: 3, trail: "Eastside Trail" },
      cuisine: ["Mexican / Tacos"], vibes: ["Groups", "Beltline access"], outdoor: ["Patio"], hours: [0, 1, 2, 3, 4, 5, 6].map(() => ["08:00", "21:00"]),
      happyHours: [{ days: WEEKDAYS, start: "15:00", end: "17:00" }],
      deals: ["food", "cocktails", "beer"], dealText: "$2.50 tacos · $2 chips & salsa · $5 margaritas · $3 Dos Equis",
      hhStatus: "confirmed", sources: [S.inf] },

    { id: "close-company", name: "Close Company", neighborhood: "Eastside Beltline",
      address: "505 N Angier Ave NE", lat: 33.76819, lng: -84.36246, price: 2, type: "Cocktail bar",
      website: "https://www.closecompanybar.com/", zip: "30308",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: [], vibes: ["Date night", "Beltline access"], outdoor: [], hours: days({ 1: ["16:00", "24:00"], 2: ["16:00", "24:00"], 3: ["16:00", "24:00"], 4: ["16:00", "24:00"], 5: ["16:00", "02:00"], 6: ["16:00", "02:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["cocktails", "food"], dealText: "$15: cocktail + pastry pocket + pickles or popcorn",
      hhStatus: "confirmed", sources: [S.inf] },

    { id: "new-realm", name: "New Realm Brewing", neighborhood: "Eastside Beltline",
      address: "550 Somerset Terrace NE", lat: 33.76903, lng: -84.36195, price: 2, type: "Brewery",
      website: "https://newrealmbrewing.com/atlanta/", zip: "30306",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["American", "Bar food"], vibes: ["Beltline access", "Groups"], outdoor: ["Rooftop", "Patio"],
      hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 5 || d === 6 ? ["11:00", "00:00"] : ["11:00", "22:00"])),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "19:00" }],
      deals: ["beer", "food"], dealText: "$5.50 craft beers · Discounted loaded fries · Discounted sliders & apps",
      hhStatus: "confirmed", sources: [{ label: "newrealmbrewing.com", url: "https://newrealmbrewing.com/atlanta/" }] },

    { id: "nine-mile", name: "9 Mile Station", neighborhood: "Eastside Beltline",
      address: "675 Ponce de Leon Ave NE (Ponce City Market rooftop)", lat: 33.77232, lng: -84.36535, price: 3, type: "Cocktail bar",
      website: "https://9milestation.com/", zip: "30308",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["American"], vibes: ["Beltline access", "Date night"], outdoor: ["Rooftop"],
      hours: days({ 0: ["11:00", "21:00"], 1: ["17:00", "22:00"], 2: ["17:00", "22:00"], 3: ["17:00", "22:00"], 4: ["17:00", "22:00"], 5: ["17:00", "00:00"], 6: ["11:00", "00:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "17:00", end: "19:00" }],
      deals: ["cocktails", "beer", "food"], dealText: "$10 cocktails: gimlet, nitro old fashioned, margarita of the day, Moscow mule · $4 Monday Night 404 lager · $35 bottles of house red, white, sparkling or rosé · $9 truffle rosemary fries · $10 spinach-artichoke dip, crispy Brussels or Nashville hot sliders · $12 mussels",
      hhStatus: "confirmed", sources: [{ label: "9milestation.com", url: "https://9milestation.com/" }] },

    { id: "superica-krog", name: "Superica Krog St", neighborhood: "Eastside Beltline",
      address: "99 Krog St NE", lat: 33.75710, lng: -84.36418, price: 2, type: "Restaurant",
      website: "https://superica.com/krog-street/", zip: "30307",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Mexican / Tacos"], vibes: ["Beltline access", "Groups"], outdoor: ["Patio"],
      hours: days({ 0: ["10:00", "22:00"], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["11:00", "23:00"], 6: ["10:00", "23:00"] }),
      happyHours: [], deals: [], dealText: "Has a happy hour menu; times not published online",
      hhStatus: "unknown", sources: [{ label: "superica.com", url: "https://superica.com/krog-street/" }] },

    { id: "ticonderoga", name: "Ticonderoga Club", neighborhood: "Eastside Beltline",
      address: "99 Krog St NE, Unit W", lat: 33.75644, lng: -84.36395, price: 3, type: "Cocktail bar",
      website: "https://www.ticonderogaclub.com/", zip: "30307",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Southern", "Seafood"], vibes: ["Date night", "Cozy", "Beltline access"], outdoor: [],
      hours: days({ 0: ["17:00", "23:00"], 1: ["17:00", "23:00"], 2: ["17:00", "23:00"], 5: ["17:00", "23:00"], 6: ["17:00", "23:00"] }),
      happyHours: [], deals: [], dealText: "No happy hour times found",
      hhStatus: "unknown", sources: [{ label: "ticonderogaclub.com", url: "https://www.ticonderogaclub.com/" }] },

    { id: "ladybird", name: "Ladybird Grove & Mess Hall", neighborhood: "Eastside Beltline",
      address: "684 John Wesley Dobbs Ave NE", lat: 33.75972, lng: -84.36460, price: 2, type: "Bar",
      website: "https://www.ladybirdatl.com/", zip: "30312",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["American", "Southern"], vibes: ["Beltline access", "Dog friendly", "Groups", "Late night"], outdoor: ["Patio"],
      hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 5 || d === 6 ? ["11:00", "02:00"] : ["11:00", "00:00"])),
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], allDay: true, rain: true, note: "$5 margs when it's raining" }],
      deals: ["cocktails"], dealText: "\"When it rains, we pour\": $5 margaritas whenever it's raining",
      hhStatus: "confirmed", sources: [{ label: "@ladybirdatlanta on Instagram", url: "https://www.instagram.com/ladybirdatlanta/" }, { label: "ladybirdatl.com", url: "https://www.ladybirdatl.com/" }] },

    { id: "two-urban-licks", name: "Two Urban Licks", neighborhood: "Eastside Beltline",
      address: "820 Ralph McGill Blvd NE", lat: 33.76850, lng: -84.36130, price: 3, type: "Restaurant",
      website: "https://www.twourbanlicks.com/", zip: "30306",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Southern", "BBQ"], vibes: ["Beltline access", "Live music"], outdoor: ["Patio"],
      hours: days({ 0: ["11:00", "22:00"], 1: ["17:00", "22:00"], 2: ["17:00", "22:00"], 3: ["17:00", "22:00"], 4: ["17:00", "22:00"], 5: ["17:00", "23:00"], 6: ["11:00", "23:00"] }),
      happyHours: [], deals: [], dealText: "Live blues Tue–Sat; happy hour times not published",
      hhStatus: "unknown", sources: [{ label: "twourbanlicks.com", url: "https://www.twourbanlicks.com/" }] },

    // ── Beltline corridor expansion (researched 2026-10-01) ───────
    { id: "lloyds", name: "LLoyd's Restaurant & Lounge", neighborhood: "Inman Park",
      address: "900 DeKalb Ave NE", lat: 33.75488, lng: -84.35796, price: 2, type: "Bar",
      website: "https://www.lloydsatl.com/", zip: "30307",
      beltline: { min: 3, trail: "Southeast Trail" },
      cuisine: ["American", "Pizza"], vibes: ["Cozy", "Late night", "Beltline access"], outdoor: [],
      hours: days({ 1: ["17:00", "23:00"], 2: ["17:00", "23:00"], 3: ["17:00", "23:00"], 4: ["17:00", "23:00"], 5: ["17:00", "00:00"], 6: ["17:00", "00:00"] }),
      happyHours: [{ days: [2, 3, 4, 5], start: "17:00", end: "19:00" }],
      deals: ["cocktails"], dealText: "$5 martinis, vespers & Manhattans",
      hhStatus: "confirmed", sources: [S.bl] },

    { id: "buena-vida", name: "Buena Vida Tapas Bar", neighborhood: "Eastside Beltline",
      address: "385 N Angier Ave NE, Ste 100", lat: 33.77040, lng: -84.36386, price: 2, type: "Restaurant",
      website: "https://www.buenavidatapas.com", zip: "30308",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Spanish / Tapas"], vibes: ["Beltline access", "Groups"], outdoor: ["Patio"], hours: days({ 0: ["11:00", "21:00"], 1: ["16:00", "21:00"], 2: ["11:30", "21:00"], 3: ["11:30", "22:00"], 4: ["11:30", "22:00"], 5: ["11:30", "23:00"], 6: ["11:00", "23:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["beer", "wine", "cocktails", "food"],
      dealText: "$5 Estrella Damm or Sweetwater 420 · $7 select wines & cava · $8 mojitos, margaritas & mules · tapas specials",
      hhStatus: "confirmed", sources: [{ label: "buenavidatapas.com", url: "https://www.buenavidatapas.com/happyhour" }] },

    { id: "mccrays-beltline", name: "McCray's Tavern on the Beltline", neighborhood: "Eastside Beltline",
      address: "670 DeKalb Ave NE", lat: 33.75407, lng: -84.36570, price: 2, type: "Bar",
      website: "https://www.mccraystavern.com/beltline", zip: "30307",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["American", "Bar food"], vibes: ["Beltline access", "Sports", "Live music"], outdoor: ["Patio"], hours: days({ 0: ["11:00", "22:00"], 1: ["16:00", "22:00"], 2: ["16:00", "22:00"], 3: ["16:00", "22:00"], 4: ["16:00", "22:00"], 5: ["16:00", "23:00"], 6: ["11:00", "23:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["food", "cocktails", "wine", "beer"], dealText: "Half-price apps · $8 draft cocktails · half off wine & pints",
      hhStatus: "confirmed", sources: [S.bl] },

    { id: "one-flew-south", name: "One Flew South Beltline", neighborhood: "Eastside Beltline",
      address: "670 DeKalb Ave NE, Ste 102", lat: 33.75368, lng: -84.36555, price: 3, type: "Restaurant",
      website: "https://oneflewsouthatl.com/beltline/", zip: "30307",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Southern"], vibes: ["Beltline access", "Date night"], outdoor: ["Patio"],
      hours: days({ 0: ["10:00", "22:00"], 3: ["15:00", "22:00"], 4: ["15:00", "22:00"], 5: ["15:00", "23:00"], 6: ["10:00", "22:00"] }),
      happyHours: [{ days: [3, 4, 5], start: "15:00", end: "17:00" }],
      deals: [], dealText: "Happy-hour cocktails: margarita, cosmo, mojito, Manhattan, gin gimlet · Beers: Sapporo, Gate City, Eventide, Allagash White, Hartsfield IPA · Wines: sparkling, merlot, albariño, pinot noir, rosé, cabernet · Bites: deviled eggs, poké tacos, smash burger, pork belly bun",
      hhStatus: "confirmed", sources: [{ label: "oneflewsouthatl.com", url: "https://oneflewsouthatl.com/beltline/" }] },

    { id: "ranger-station", name: "Ranger Station", neighborhood: "Eastside Beltline",
      address: "684 John Wesley Dobbs Ave NE", lat: 33.75982, lng: -84.36467, price: 2, type: "Cocktail bar",
      website: "https://www.rangerstationatl.com/", zip: "30312",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: [], vibes: ["Cozy", "Date night", "Beltline access"], outdoor: [],
      hours: days({ 0: ["17:00", "00:00"], 1: ["17:00", "00:00"], 2: ["17:00", "00:00"], 3: ["17:00", "00:00"], 4: ["17:00", "00:00"], 5: ["17:00", "01:00"], 6: ["17:00", "01:00"] }),
      happyHours: [], deals: [], dealText: "Listed as having a happy hour; times not published",
      hhStatus: "unknown", sources: [{ label: "The Infatuation review", url: "https://www.theinfatuation.com/atlanta/reviews/ranger-station" }] },

    { id: "burles", name: "Burle's Bar", neighborhood: "Eastside Beltline",
      address: "505 N Angier Ave NE (The Victorian)", lat: 33.76830, lng: -84.36253, price: 2, type: "Cocktail bar",
      website: "https://www.burlesbar.com/", zip: "30308",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Pizza"], vibes: ["Live music", "Cozy", "Beltline access"], outdoor: [],
      hours: days({ 0: ["12:00", "22:00"], 2: ["15:00", "00:00"], 3: ["15:00", "00:00"], 4: ["15:00", "00:00"], 5: ["15:00", "00:00"], 6: ["12:00", "00:00"] }),
      happyHours: [], deals: [], dealText: "Live jazz Tuesdays; no happy hour listed on their site",
      hhStatus: "unknown", sources: [{ label: "burlesbar.com", url: "https://www.burlesbar.com/" }] },

    { id: "el-super-pan", name: "El Super Pan", neighborhood: "Eastside Beltline",
      address: "675 Ponce de Leon Ave NE (Ponce City Market)", lat: 33.77242, lng: -84.36542, price: 1, type: "Restaurant",
      website: "https://www.elsuperpan.com/ponce-city-market", zip: "30308",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: ["Latin", "Sandwiches"], vibes: ["Groups", "Live music", "Beltline access"], outdoor: [], hours: days({ 0: ["09:00", "20:00"], 1: ["09:00", "21:00"], 2: ["09:00", "21:00"], 3: ["09:00", "21:00"], 4: ["09:00", "21:00"], 5: ["09:00", "23:00"], 6: ["09:00", "23:00"] }),
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "16:00", end: "19:00" }],
      deals: ["beer", "cocktails", "food"], dealText: "Boricua Happy Hour daily from 4PM · $5 beers · $6 rum punch",
      hhStatus: "reported", sources: [{ label: "elsuperpan.com", url: "https://www.elsuperpan.com/ponce-city-market" }, { label: "AJC", url: "https://www.ajc.com/blog/atlanta-restaurants/eat-drink-and-dance-during-happy-hour-fridays-this-ponce-city-market-spot/iNTe7w5b7pDjx86Q4idMoN/" }] },

    { id: "twelve-cocktail", name: "12 Cocktail Bar", neighborhood: "Eastside Beltline",
      address: "675 Ponce de Leon Ave NE (Ponce City Market tower)", lat: 33.77222, lng: -84.36542, price: 3, type: "Cocktail bar",
      website: "https://www.12cocktailbar.com/", zip: "30308",
      beltline: { min: 1, trail: "Eastside Trail" },
      cuisine: [], vibes: ["Date night", "Cozy", "Beltline access"], outdoor: [], hours: null,
      happyHours: [], deals: ["cocktails", "food"], dealText: "Hidden bar, open Mon–Sat from 5PM; has a happy hour menu (\"tiny tinis & salty snacks\") but no posted times",
      hhStatus: "unknown", sources: [{ label: "12cocktailbar.com", url: "https://www.12cocktailbar.com/" }] },

    // ── Old Fourth Ward / Krog / Edgewood sweep (2026-10-05) ──
    { id: "hawkers-beltline", name: "Hawkers Asian Street Food", neighborhood: "Eastside Beltline",
      address: "661 Auburn Ave NE, Unit 180", lat: 33.75563, lng: -84.36553, price: 2, type: "Restaurant",
      beltline: { min: 1, trail: "Eastside Trail" }, website: "https://eathawkers.com/locations/beltline/", zip: "30312",
      cuisine: ["Asian"], vibes: ["Groups", "Beltline access"], outdoor: [], hours: null,
      happyHours: [{ days: [1, 2, 3, 4], start: "15:00", end: "18:00" }],
      deals: ["beer", "food", "cocktails"], dealText: "Half-off baos & beers · $3 off all spirits · $5 select small plates",
      hhStatus: "confirmed", sources: [{ label: "eathawkers.com", url: "https://eathawkers.com/locations/beltline/" }] },
    { id: "el-ponce", name: "El Ponce", neighborhood: "Poncey-Highland",
      address: "939 Ponce de Leon Ave NE", lat: 33.77355, lng: -84.35665, price: 1, type: "Restaurant",
      website: "https://www.elponce.com/", zip: "30306",
      cuisine: ["Mexican / Tacos"], vibes: ["Groups"], outdoor: [], hours: null,
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "16:00", end: "18:00" }],
      deals: ["cocktails", "beer", "food"], dealText: "$7 margaritas, Mexican mules, palomas & micheladas · $3 botanas (mini quesadillas, flautas, esquite & more) · $2 off flights · dine-in only",
      hhStatus: "confirmed", sources: [{ label: "El Ponce happy hour menu", url: "https://www.elponce.com/s/Happy-Hour-Menu-v2.jpg" }] },
    { id: "wylie-rum", name: "Wylie & Rum", neighborhood: "Edgewood",
      address: "45 Moreland Ave SE, Suite 300", lat: 33.75218, lng: -84.34957, price: 2, type: "Restaurant",
      website: "https://wylieandrum.com/", zip: "30316",
      cuisine: ["Caribbean"], vibes: ["Groups"], outdoor: [], hours: days({ 0: ["11:00", "21:00"], 1: ["11:00", "21:00"], 2: ["11:00", "21:00"], 3: ["11:00", "21:00"], 4: ["11:00", "21:00"], 5: ["11:00", "22:00"], 6: ["11:00", "22:00"] }),
      happyHours: [
        { days: [1], allDay: true, note: "Mojito Monday" },
        { days: [2], allDay: true, note: "Mai Tai Tuesday: half price" },
        { days: [3], allDay: true, note: "Rum Punch Wednesday" },
        { days: [4], allDay: true, note: "Margarita Thursday" },
        { days: [5], allDay: true, note: "Moscow Mule Friday" },
      ],
      deals: ["cocktails"], dealText: "Mon: Mojito Monday · Tue: half-price Mai Tais · Wed: Rum Punch Wednesday · Thu: Margarita Thursday · Fri: Moscow Mule Friday · Bottomless mimosas at weekend brunch",
      hhStatus: "confirmed", sources: [{ label: "wylieandrum.com (specials)", url: "https://wylieandrum.com/atlanta-reynoldstown-wylie-and-rum-happy-hours-specials" }] },
    { id: "lingering-shade", name: "Lingering Shade Social Club", neighborhood: "Eastside Beltline",
      address: "660 Irwin St NE", lat: 33.75778, lng: -84.36504, price: 2, type: "Cocktail bar",
      beltline: { min: 1, trail: "Eastside Trail" }, website: "https://www.lingeringshade.com/", zip: "30312",
      cuisine: [], vibes: ["Cozy", "Date night", "Beltline access"], outdoor: ["Patio"], hours: days({ 0: ["14:00", "22:00"], 1: ["16:00", "22:00"], 2: ["16:00", "22:00"], 3: ["16:00", "22:00"], 4: ["16:00", "22:00"], 5: ["16:00", "24:00"], 6: ["14:00", "24:00"] }),
      happyHours: [{ days: [1, 2], start: "16:00", end: "22:00", note: "Half-price wine bottles" }, { days: [3, 4], start: "16:00", end: "22:00", note: "$9 weekly special cocktail" }],
      deals: ["wine", "cocktails"], dealText: "Mon–Tue: half-price bottles of wine · Wed–Thu: $9 special cocktail (changes weekly)",
      hhStatus: "reported", sources: [{ label: "Georgia on My Dime", url: "https://georgiaonmydime.com/atlanta-happy-hour/lingering-shade/" }, { label: "lingeringshade.com (hours)", url: "https://www.lingeringshade.com/" }] },

    // ── Reynoldstown ──────────────────────────────────────────────
    { id: "muchacho", name: "Muchacho", neighborhood: "Reynoldstown",
      address: "904 Memorial Dr SE", lat: 33.74687, lng: -84.35799, price: 1, type: "Restaurant",
      website: "https://muchacho.com/", zip: "30316",
      beltline: { min: 1, trail: "Southeast Trail" },
      cuisine: ["Mexican / Tacos"], vibes: ["Groups", "Beltline access"], outdoor: ["Patio"],
      hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 5 || d === 6 ? ["08:00", "23:00"] : ["08:00", "22:00"])),
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "15:00", end: "18:00" }],
      deals: ["cocktails", "food"], dealText: "\"Staring at the Sun\" menu: select snacks & drinks $5 at the bar",
      hhStatus: "reported", sources: [{ label: "muchacho.com", url: "https://muchacho.com/" }] },

    { id: "breaker-breaker", name: "Breaker Breaker", neighborhood: "Reynoldstown",
      address: "921 Wylie St SE", lat: 33.75207, lng: -84.35687, price: 2, type: "Restaurant",
      website: "https://www.breakerbreakeratl.com/", zip: "30316",
      beltline: { min: 1, trail: "Southeast Trail" },
      cuisine: ["Seafood", "Cajun"], vibes: ["Beltline access"], outdoor: ["Rooftop", "Patio"], hours: null,
      happyHours: [], deals: [], dealText: "Happy hour Wed, Thu & Sun (times not published) · rooftop bar Florida Man is 21+",
      hhStatus: "unknown", sources: [{ label: "breakerbreakeratl.com", url: "https://www.breakerbreakeratl.com/home" }] },

    // ── Little Five Points ────────────────────────────────────────
    { id: "star-bar", name: "Star Community Bar", neighborhood: "Little Five Points",
      address: "437 Moreland Ave NE", lat: 33.76625, lng: -84.34882, price: 1, type: "Dive bar",
      website: "https://www.starbaratl.bar/", zip: "30307",
      cuisine: [], vibes: ["Live music", "Late night"], outdoor: [],
      hours: days({ 0: ["13:00", "00:00"], 1: ["17:00", "02:30"], 2: ["17:00", "02:30"], 3: ["17:00", "02:30"], 4: ["17:00", "02:30"], 5: ["13:00", "02:30"], 6: ["13:00", "02:30"] }),
      happyHours: [], deals: ["beer"], dealText: "Everyday cheap drinks ($4 beer specials) rather than a set happy hour",
      hhStatus: "unknown", sources: [{ label: "starbaratl.bar", url: "https://www.starbaratl.bar/" }] },

    { id: "yacht-club", name: "Euclid Avenue Yacht Club", neighborhood: "Little Five Points",
      address: "1136 Euclid Ave NE", lat: 33.76484, lng: -84.35011, price: 1, type: "Dive bar",
      website: "http://theeayc.com", zip: "30307",
      cuisine: ["BBQ", "Bar food"], vibes: ["Late night", "Cozy"], outdoor: [],
      hours: [0, 1, 2, 3, 4, 5, 6].map(() => ["12:00", "03:00"]),
      happyHours: [], deals: [], dealText: "Daily food & drink specials; happy hour times not published",
      hhStatus: "unknown", sources: [{ label: "Yelp listing", url: "https://www.yelp.com/biz/the-euclid-avenue-yacht-club-atlanta" }] },

    // ── Midtown ───────────────────────────────────────────────────
    { id: "holeman-finch", name: "Holeman & Finch Public House", neighborhood: "Midtown",
      address: "1201 Peachtree St NE (Colony Square)", lat: 33.78790, lng: -84.38306, price: 3, type: "Bar",
      website: "https://www.holeman-finch.com/", zip: "30361",
      cuisine: ["American", "Seafood"], vibes: ["Date night"], outdoor: ["Patio"], hours: days({ 0: ["11:00", "21:00"], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "23:00"], 5: ["11:00", "23:00"], 6: ["11:00", "23:00"] }),
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "16:00", end: "18:00" }],
      deals: ["oysters", "food", "cocktails"], dealText: "Half-off oysters on the half shell · $12 fried oyster babies · $10–12 cocktails: Teeny Tini, Half Fashioned, Hemingway Jr., Barely Famous · $12 house bubbly, white & red · Snacks $7–12: mini cheeseburger, The Parisian, pork cracklin', cheese straws",
      hhStatus: "confirmed", sources: [S.cs, S.inf] },

    { id: "5church", name: "5Church Midtown", neighborhood: "Midtown",
      address: "Colony Square, 1197 Peachtree St NE", lat: 33.78728, lng: -84.38278, price: 3, type: "Restaurant",
      website: "https://midtown.5church-atlanta.com/", zip: "30361",
      cuisine: ["American", "Seafood"], vibes: ["Date night", "Live music"], outdoor: ["Patio", "Rooftop"], hours: days({ 0: [["11:00", "16:00"], ["18:00", "21:30"]], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["11:00", "23:00"], 6: [["11:00", "15:00"], ["17:00", "23:00"]] }),
      happyHours: [{ days: WEEKDAYS, start: "15:00", end: "19:00" }],
      deals: ["oysters"], dealText: "$1 oysters · Bar & front lounge only, dine-in",
      hhStatus: "confirmed", sources: [S.cs] },

    { id: "establishment", name: "Establishment", neighborhood: "Midtown",
      address: "1197 Peachtree St NE (Colony Square)", lat: 33.78685, lng: -84.38217, price: 2, type: "Bar",
      website: "https://establishmentatlanta.com/", zip: "30361",
      cuisine: ["American"], vibes: ["Date night"], outdoor: [], hours: days({ 1: [["11:30", "15:00"], ["16:00", "22:00"]], 2: [["11:30", "15:00"], ["16:00", "22:00"]], 3: [["11:30", "15:00"], ["16:00", "22:00"]], 4: [["11:30", "15:00"], ["16:00", "22:00"]], 5: [["11:30", "15:00"], ["16:00", "23:00"]], 6: ["16:30", "23:00"] }),
      happyHours: [{ days: [1, 2, 3, 4, 5, 6], start: "15:00", end: "19:00" }],
      deals: ["cocktails", "food"], dealText: "$9 cocktails · $10 confit duck tacos · Mon: steak, fries & martini $32",
      hhStatus: "confirmed", sources: [S.cs, S.inf] },

    { id: "serena", name: "Serena Pastificio", neighborhood: "Midtown",
      address: "Colony Square, 1197 Peachtree St NE", lat: 33.78738, lng: -84.38285, price: 2, type: "Restaurant",
      website: "https://www.serena-pastificio.com/",
      zip: "30361",
      cuisine: ["Italian"], vibes: ["Date night"], outdoor: [], hours: null,
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "15:00", end: "18:00" }],
      deals: ["food", "cocktails"], dealText: "Discounted small plates & cocktails",
      hhStatus: "confirmed", sources: [S.cs] },

    { id: "park-tavern", name: "Park Tavern", neighborhood: "Midtown",
      address: "500 10th St NE (Piedmont Park)", lat: 33.78215, lng: -84.36924, price: 2, type: "Bar",
      website: "https://www.parktavern.com/", zip: "30309",
      beltline: { min: 1, trail: "Northeast Trail" },
      cuisine: ["American", "Bar food"], vibes: ["Sports", "Groups", "Dog friendly", "Beltline access"], outdoor: ["Patio"], hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 0 || d === 6 ? ["11:00", "24:00"] : ["16:30", "24:00"])),
      happyHours: [{ days: WEEKDAYS, start: "16:30", end: "18:00" }, { days: [0, 1, 2, 3, 4], start: "20:00", end: "24:00", note: "Late happy hour (8PM–close)" }],
      deals: ["beer", "wine", "cocktails", "food"], dealText: "$1 off all drinks · Food $6–10",
      hhStatus: "confirmed", sources: [{ label: "parktavern.net", url: "https://www.parktavern.net/menu/happy-hour-menu/" }, S.ramb] },

    { id: "cypress-street", name: "Cypress Street Pint & Plate", neighborhood: "Midtown",
      address: "817 W Peachtree St NE", lat: 33.77735, lng: -84.38611, price: 1, type: "Bar",
      website: "https://cypressatl.com/", zip: "30308",
      cuisine: ["Bar food", "American"], vibes: ["Groups", "Sports"], outdoor: ["Patio"], hours: days({ 0: ["10:00", "24:00"], 1: ["11:00", "24:00"], 2: ["11:00", "24:00"], 3: ["11:00", "24:00"], 4: ["11:00", "24:00"], 5: ["11:00", "24:00"], 6: ["10:00", "24:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "17:00", end: "19:00" }, { days: [4], allDay: true, note: "$2 tacos & half-off wine" }],
      deals: ["food", "wine", "beer"], dealText: "No happy hour on its site, only rotating monthly specials (Sept 2026: $3 Taco Monday with a drink)",
      hhStatus: "unknown", sources: [{ label: "cypressatl.com", url: "https://cypressatl.com/" }] },

    { id: "boho-taco", name: "Boho Taco Tech Square", neighborhood: "Midtown",
      address: "22 5th St NW (Tech Square)", lat: 33.77665, lng: -84.38790, price: 1, type: "Restaurant",
      website: "https://eatboho.com/", zip: "30308",
      cuisine: ["Mexican / Tacos"], vibes: ["Groups"], outdoor: [], hours: [0, 1, 2, 3, 4, 5, 6].map(() => ["11:00", "22:00"]),
      happyHours: [{ days: [1], allDay: true, note: "$5 Margarita Monday" }],
      deals: ["cocktails"], dealText: "$5 house margaritas every Monday",
      hhStatus: "confirmed", sources: [{ label: "Instagram @eatboho (Sep 21, 2026)", url: "https://www.instagram.com/eatboho/" }] },

    // ── Midtown / Atlantic Station sweep (2026-10-05) ──
    { id: "altatoro", name: "AltaToro", neighborhood: "Midtown",
      address: "33 Peachtree Pl NE", lat: 33.78055, lng: -84.38714, price: 2, type: "Restaurant",
      website: "https://altatoro.com/", zip: "30309",
      cuisine: ["Latin", "Seafood"], vibes: ["Date night", "Groups"], outdoor: ["Patio"], hours: null,
      happyHours: [
        { days: [0, 1, 2, 3, 4, 5], start: "15:00", end: "19:00", note: "Bar & front lounge" },
      ],
      deals: ["oysters", "cocktails", "beer", "wine", "food"], dealText: "$1 oysters · frozen margaritas, sangria, wine & beer specials · shareable bar bites",
      hhStatus: "confirmed", sources: [{ label: "altatoro.com", url: "https://altatoro.com/" }] },
    { id: "casa-almenara", name: "Casa Almenara", neighborhood: "Midtown",
      address: "991 Piedmont Ave NE", lat: 33.78164, lng: -84.3803, price: 2, type: "Restaurant",
      website: "https://casa-almenara.com/", zip: "30309",
      cuisine: ["Mexican / Tacos", "Mediterranean"], vibes: ["Groups", "Late night"], outdoor: ["Patio"], hours: days({ 0: ["11:00", "24:00"], 1: ["14:00", "24:00"], 2: ["14:00", "24:00"], 3: ["14:00", "02:00"], 4: ["14:00", "02:00"], 5: ["14:00", "02:00"], 6: ["11:00", "02:00"] }),
      happyHours: [
        { days: [0, 1, 2, 3, 4, 5, 6], start: "16:00", end: "19:00" },
        { days: [2], allDay: true, note: "Taco & Tequila Tuesday" },
      ],
      deals: ["cocktails", "beer", "food"], dealText: "Daily 4–7 happy hour, weekends included · Taco & Tequila Tuesday: $5 margaritas · $3 Tecate & $3 tacos on Tuesdays · Half-price nachos on Tuesdays",
      hhStatus: "confirmed", sources: [{ label: "casa-almenara.com", url: "https://casa-almenara.com/" }] },
    { id: "livingston", name: "Livingston Restaurant + Bar", neighborhood: "Midtown",
      address: "659 Peachtree St NE (Georgian Terrace)", lat: 33.77241, lng: -84.38469, price: 3, type: "Restaurant",
      website: "https://www.livingstonatl.com/", zip: "30308",
      cuisine: ["Southern", "American"], vibes: ["Date night"], outdoor: ["Patio"], hours: null,
      happyHours: [
        { days: [0, 1, 2, 3, 4, 5, 6], start: "16:00", end: "19:00", note: "8–10 PM instead on Fox Theatre show days" },
      ],
      deals: ["cocktails", "wine", "beer", "food"], dealText: "$9 cocktails · $7 house wine · $6 beer · light bites $8–12 · On Fox Theatre show nights, happy hour moves to 8–10 PM",
      hhStatus: "confirmed", sources: [{ label: "Livingston happy hour menu (PDF)", url: "https://www.livingstonatl.com/s/happy-Hour-Menu-2025-PDF.pdf" }] },
    { id: "ponce-room", name: "The Ponce Room", neighborhood: "Midtown",
      address: "640 Peachtree St NE", lat: 33.77213, lng: -84.38513, price: 2, type: "Restaurant",
      website: "https://www.theponceroom.com/", zip: "30308",
      cuisine: ["Southern"], vibes: ["Groups"], outdoor: [], hours: days({ 0: [["10:00", "15:00"], ["16:00", "22:00"]], 1: ["17:00", "22:00"], 2: ["17:00", "22:00"], 3: ["17:00", "22:00"], 4: ["17:00", "22:00"], 5: ["16:00", "23:00"], 6: [["10:00", "15:00"], ["16:00", "23:00"]] }),
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "17:00", end: "18:30" },
      ],
      deals: ["cocktails", "beer", "wine", "food"], dealText: "$10 cocktails · $6 canned beer · $7 wine & shots · snacks $7–10 (wings, cheese curds, poke nachos)",
      hhStatus: "confirmed", sources: [{ label: "theponceroom.com/happy-hour", url: "https://www.theponceroom.com/happy-hour" }] },
    { id: "stk-atlanta", name: "STK Steakhouse", neighborhood: "Midtown",
      address: "1075 Peachtree St NE", lat: 33.78418, lng: -84.38293, price: 3, type: "Restaurant",
      website: "https://stksteakhouse.com/venues/atlanta/", zip: "30309",
      cuisine: ["Steakhouse"], vibes: ["Date night", "Late night"], outdoor: [], hours: null,
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "14:30", end: "18:30" },
        { days: [0, 6], start: "14:30", end: "17:30" },
        { days: [0, 1, 2, 3, 4], start: "21:00", end: "close", note: "Late-night social hour" },
      ],
      deals: ["cocktails", "food"], dealText: "$3 bites · $6 bites & cocktails · $9 cocktails · Late-night Social Hour Sun–Thu from 9PM",
      hhStatus: "confirmed", sources: [{ label: "stksteakhouse.com", url: "https://stksteakhouse.com/venues/atlanta/" }] },
    { id: "boqueria-atl", name: "Boqueria", neighborhood: "Midtown",
      address: "1221 Peachtree St NE (Colony Square)", lat: 33.788, lng: -84.38333, price: 2, type: "Restaurant",
      website: "https://boqueriarestaurant.com/location/atl-colony-square/", zip: "30361",
      cuisine: ["Spanish / Tapas"], vibes: ["Groups", "Date night"], outdoor: [], hours: days({ 0: ["11:00", "22:00"], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["11:00", "23:00"], 6: ["11:00", "23:00"] }),
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "15:00", end: "18:00" },
        { days: [0, 6], start: "16:00", end: "18:00" },
      ],
      deals: ["food", "cocktails"], dealText: "$7 tapas: jamón croquetas, patatas bravas, PX wings · Social Hour drink specials",
      hhStatus: "confirmed", sources: [{ label: "boqueriarestaurant.com", url: "https://boqueriarestaurant.com/location/atl-colony-square/" }] },
    { id: "sebastian-pintxos", name: "Sebastián Pintxos Bar", neighborhood: "Midtown",
      address: "818 Juniper St NE", lat: 33.77688, lng: -84.38308, price: 2, type: "Restaurant",
      website: "https://www.sebastianpintxosbar.com/", zip: "30308",
      cuisine: ["Spanish / Tapas"], vibes: ["Late night", "Live music", "Groups"], outdoor: ["Patio"], hours: days({ 0: ["12:00", "24:00"], 1: ["12:00", "24:00"], 2: ["12:00", "01:00"], 3: ["12:00", "01:00"], 4: ["12:00", "01:00"], 5: ["12:00", "03:00"], 6: ["12:00", "03:00"] }),
      happyHours: [
        { days: [1], allDay: true },
        { days: [2, 3, 4, 5], start: "12:00", end: "17:00" },
        { days: [2], allDay: true, note: "Taco Tuesday" },
        { days: [3], allDay: true, note: "Half-off wine bottles" },
      ],
      deals: ["cocktails", "wine", "food"], dealText: "Happy hour all day Monday, noon–5 Tue–Fri · rotating tapas & cocktail specials · Taco Tuesday · half-off wine bottles Wednesday",
      hhStatus: "confirmed", sources: [{ label: "sebastianpintxosbar.com/happy-hour", url: "https://www.sebastianpintxosbar.com/happy-hour" }] },
    { id: "ecco-midtown", name: "Ecco Midtown", neighborhood: "Midtown",
      address: "40 7th St NE", lat: 33.77878, lng: -84.38588, price: 2, type: "Restaurant",
      website: "https://www.ecco-atlanta.com/location/midtown", zip: "30308",
      cuisine: ["Italian", "Mediterranean"], vibes: ["Date night"], outdoor: ["Patio"], hours: days({ 0: ["17:00", "21:00"], 1: ["16:00", "21:30"], 2: ["16:00", "21:30"], 3: ["16:00", "21:30"], 4: ["16:00", "21:30"], 5: ["16:00", "22:00"], 6: ["17:00", "22:00"] }),
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "16:00", end: "18:00" },
      ],
      deals: ["cocktails", "wine", "beer", "food"], dealText: "$7 cocktails: limoncello spritz, margarita, old fashioned · $7 wine & beer · Small plates $6–17",
      hhStatus: "confirmed", sources: [{ label: "ecco-atlanta.com happy hour menu", url: "https://www.ecco-atlanta.com/menu-midtown#menu=midtown-happy-hour" }] },
    { id: "south-city-midtown", name: "South City Kitchen Midtown", neighborhood: "Midtown",
      address: "1144 Crescent Ave NE", lat: 33.786, lng: -84.38446, price: 2, type: "Restaurant",
      website: "https://www.southcitykitchen.com/", zip: "30309",
      cuisine: ["Southern"], vibes: ["Date night"], outdoor: ["Patio"], hours: days({ 0: [["10:00", "15:00"], ["17:00", "21:00"]], 1: [["11:00", "14:30"], ["16:00", "21:00"]], 2: [["11:00", "14:30"], ["16:00", "21:00"]], 3: [["11:00", "14:30"], ["16:00", "21:00"]], 4: [["11:00", "14:30"], ["16:00", "21:00"]], 5: [["11:00", "14:30"], ["16:00", "22:00"]], 6: [["10:00", "15:00"], ["17:00", "22:00"]] }),
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "16:00", end: "18:00" },
      ],
      deals: ["cocktails", "wine", "beer", "food"], dealText: "$7 cocktails & wine · $5 SweetWater · Fried green tomatoes $8 · Pimento cheese & deviled eggs $7",
      hhStatus: "confirmed", sources: [{ label: "southcitykitchen.com", url: "https://www.southcitykitchen.com/events/happy-hour-2" }] },
    { id: "dos-caminos-atl", name: "Dos Caminos", neighborhood: "Midtown",
      address: "1100 Peachtree St NE", lat: 33.78452, lng: -84.38326, price: 2, type: "Restaurant",
      website: "https://www.doscaminos.com/location/atlanta/", zip: "30309",
      cuisine: ["Mexican / Tacos"], vibes: ["Groups"], outdoor: ["Patio"], hours: days({ 0: ["11:30", "21:00"], 1: ["11:30", "21:00"], 2: ["11:30", "21:00"], 3: ["11:30", "21:00"], 4: ["11:30", "21:00"], 5: ["11:30", "22:00"], 6: ["11:30", "22:00"] }),
      happyHours: [
        { days: [0, 1, 2, 3, 4, 5, 6], start: "11:30", end: "19:00", note: "Bar & patio" },
      ],
      deals: ["cocktails", "beer", "food"], dealText: "Bar & patio: chips & guac or queso $10, flautas & empanadas $12 · $8 margaritas Mon · $4 tacos Tue · $5 drafts Thu · $8 frozen margs Fri",
      hhStatus: "confirmed", sources: [{ label: "doscaminos.com", url: "https://www.doscaminos.com/event/happy-hour-atlanta/" }] },
    { id: "hudson-grille-midtown", name: "Hudson Grille Midtown", neighborhood: "Midtown",
      address: "942 Peachtree St NE", lat: 33.78039, lng: -84.38433, price: 2, type: "Sports bar",
      website: "https://hudsongrille.com/", zip: "30309",
      cuisine: ["Bar food", "American"], vibes: ["Sports", "Groups"], outdoor: ["Patio"], hours: null,
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "15:00", end: "18:00" },
      ],
      deals: ["food"], dealText: "Half-price appetizers weekdays 3–6 (dine-in)",
      hhStatus: "reported", sources: [{ label: "hudsongrille.com (specials)", url: "https://hudsongrille.com/page/specials" }] },
    { id: "brasserie-lundi", name: "Brasserie Lundi", neighborhood: "Midtown",
      address: "1375 Peachtree St NE", lat: 33.79252, lng: -84.38605, price: 3, type: "Restaurant",
      website: "https://brasserielundi.com/", zip: "30309",
      cuisine: ["French"], vibes: ["Date night"], outdoor: [], hours: days({ 0: ["17:00", "22:00"], 1: ["17:00", "22:00"], 2: ["17:00", "22:00"], 3: ["17:00", "22:00"], 4: ["17:00", "22:00"], 5: ["17:00", "23:00"], 6: ["17:00", "23:00"] }),
      happyHours: [
        { days: [1], allDay: true, note: "Half-price wine bottles" },
      ],
      deals: ["wine"], dealText: "Half Price Mondays: half off select bottles of wine all day",
      hhStatus: "confirmed", sources: [{ label: "brasserielundi.com", url: "https://brasserielundi.com/" }] },
    { id: "gyu-kaku-atlantic", name: "Gyu-Kaku Japanese BBQ", neighborhood: "Atlantic Station",
      address: "265 18th St NW, #4130", lat: 33.79284, lng: -84.39668, price: 2, type: "Restaurant",
      website: "https://www.gyu-kaku.com/atlanta/", zip: "30363",
      cuisine: ["Asian"], vibes: ["Groups"], outdoor: [], hours: days({ 0: ["11:30", "22:00"], 1: ["11:30", "22:00"], 2: ["11:30", "22:00"], 3: ["11:30", "22:00"], 4: ["11:30", "22:00"], 5: ["11:30", "22:30"], 6: ["11:30", "22:30"] }),
      happyHours: [
        { days: [1, 2, 3, 4], start: "11:30", end: "17:00" },
        { days: [1, 2, 3, 4], start: "20:30", end: "22:00", note: "Late happy hour" },
        { days: [0, 5, 6], start: "11:30", end: "17:00" },
      ],
      deals: ["food", "beer", "cocktails"], dealText: "Happy-hour prices on grill meats · Discounted apps · Drink specials · Late happy hour 8:30–10PM Mon–Thu",
      hhStatus: "confirmed", sources: [{ label: "gyu-kaku.com/atlanta", url: "https://www.gyu-kaku.com/atlanta/" }] },
    { id: "srithai-atlantic", name: "SriThai Kitchen & Bar", neighborhood: "Atlantic Station",
      address: "1380 Atlantic Dr NW", lat: 33.79344, lng: -84.39774, price: 2, type: "Restaurant",
      website: "https://srithaikitchen.com/", zip: "30363",
      cuisine: ["Thai", "Sushi"], vibes: ["Groups"], outdoor: ["Patio"], hours: days({ 0: ["12:00", "22:00"], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["10:30", "23:00"], 6: ["12:00", "23:00"] }),
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "15:00", end: "18:00" },
        { days: [1, 2], start: "17:00", end: "21:00", note: "Sushi Night" },
        { days: [3], start: "18:00", end: "22:00", note: "Ladies' Night" },
      ],
      deals: ["cocktails", "food"], dealText: "Drink & appetizer deals weekdays 3–6 · Sushi Night Mon–Tue · Ladies' Night Wed",
      hhStatus: "confirmed", sources: [{ label: "srithaikitchen.com", url: "https://srithaikitchen.com/" }] },

    // ── West Midtown / Home Park (Georgia Tech) ───────────────────
    { id: "rocky-mountain", name: "Rocky Mountain Pizza", neighborhood: "Home Park",
      address: "1005 Hemphill Ave NW", lat: 33.78212, lng: -84.40435, price: 1, type: "Restaurant",
      website: "https://www.rockymountainpizza.com/", zip: "30318",
      cuisine: ["Pizza", "Bar food"], vibes: ["Sports", "Groups"], outdoor: ["Patio"], hours: days({ 0: ["12:00", "23:00"], 1: ["11:00", "24:00"], 2: ["11:00", "24:00"], 3: ["11:00", "24:00"], 4: ["11:00", "24:00"], 5: ["11:00", "01:00"], 6: ["12:00", "01:00"] }),
      happyHours: [{ days: [1, 2, 3, 4], allDay: true, note: "Discounted beers & margaritas" }],
      deals: ["beer", "cocktails"], dealText: "Mon–Thu all-day beer & margarita specials",
      hhStatus: "reported", sources: [S.ramb] },

    { id: "ghee", name: "Ghee Indian Kitchen", neighborhood: "West Midtown",
      address: "1050 Howell Mill Rd", lat: 33.78345, lng: -84.41189, price: 2, type: "Restaurant",
      website: "https://www.gheeindiankitchen.com/location/ghee-westmidtown/",
      zip: "30318",
      cuisine: ["Indian"], vibes: ["Groups"], outdoor: [], hours: null,
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "17:00", end: "19:00" }],
      deals: ["food", "cocktails"], dealText: "Specials under $5, $10 & $15",
      hhStatus: "confirmed", sources: [S.inf] },

    { id: "flight-club", name: "Flight Club", neighborhood: "West Midtown",
      address: "1055 Howell Mill Rd NW", lat: 33.78334, lng: -84.41142, price: 2, type: "Bar",
      website: "https://flightclubdartsusa.com/atlanta", zip: "30318",
      cuisine: ["American"], vibes: ["Groups", "Games"], outdoor: [], hours: days({ 0: ["11:00", "21:00"], 1: ["16:00", "23:00"], 2: ["16:00", "23:00"], 3: ["16:00", "23:00"], 4: ["16:00", "23:00"], 5: ["16:00", "24:00"], 6: ["11:00", "24:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["food", "cocktails", "beer", "wine"], dealText: "$10 buffalo chicken sliders · $12 flatbreads · $8 cocktails all day Mondays",
      hhStatus: "confirmed", sources: [S.inf, S.bl] },

    { id: "ormsbys", name: "Ormsby's", neighborhood: "West Midtown",
      address: "1170 Howell Mill Rd, Ste P20", lat: 33.78576, lng: -84.41204, price: 1, type: "Bar",
      website: "https://www.ormsbysatlanta.com/", zip: "30318",
      cuisine: ["Bar food", "Sandwiches"], vibes: ["Games", "Groups", "Sports"], outdoor: ["Patio"], hours: null,
      happyHours: [], deals: [], dealText: "Bocce, shuffleboard & darts; a Georgia Tech favorite. Happy hour times not published",
      hhStatus: "unknown", sources: [{ label: "ormsbysatlanta.com", url: "https://www.ormsbysatlanta.com/" }] },

    // ── Toco Hills / North Decatur (Emory) ────────────────────────
    { id: "wild-heaven-toco", name: "Wild Heaven + Fox Bros. Toco Hills", neighborhood: "Toco Hills",
      address: "2935-B N Druid Hills Rd NE", lat: 33.81538, lng: -84.31018, price: 1, type: "Brewery",
      website: "https://wildheavenbeer.com/toco-hills", zip: "30329",
      cuisine: ["BBQ"], vibes: ["Dog friendly", "Groups", "Sports"], outdoor: ["Patio"],
      hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 0 ? ["11:00", "20:00"] : d >= 5 ? ["11:00", "22:00"] : ["11:00", "21:00"])),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }],
      deals: ["beer", "wine", "cocktails"], dealText: "$5 EDB pints · $6 drafts · $7 wine · $8 cocktails",
      hhStatus: "confirmed", sources: [{ label: "wildheavenbeer.com", url: "https://wildheavenbeer.com/toco-hills" }] },

    { id: "maggies", name: "Maggie's Neighborhood Bar", neighborhood: "Toco Hills",
      address: "2937 N Druid Hills Rd NE", lat: 33.81491, lng: -84.31219, price: 1, type: "Dive bar",
      website: "https://www.maggiestocohills.com/", zip: "30329",
      cuisine: ["Bar food"], vibes: ["Late night", "Sports"], outdoor: [],
      hours: [0, 1, 2, 3, 4, 5, 6].map(() => ["12:00", "02:00"]),
      happyHours: [{ days: [1], allDay: true, note: "Margarita Monday" }, { days: [2], allDay: true, note: "$2 tequila shots, $3 tequila drinks" }],
      deals: ["cocktails"], dealText: "$4 lemon drop shots daily · Tequila Tuesday",
      hhStatus: "reported", sources: [{ label: "maggiestocohills.com", url: "https://www.maggiestocohills.com/" }] },

    { id: "salaryman-toco", name: "Salaryman Toco Hills", neighborhood: "Toco Hills",
      address: "2941 N Druid Hills Rd NE, Ste B", lat: 33.81523, lng: -84.31006, price: 2, type: "Restaurant",
      website: "https://www.salarymanatl.com/", zip: "30329",
      cuisine: ["Asian"], vibes: ["Groups"], outdoor: [], hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 5 || d === 6 ? ["11:30", "22:30"] : ["11:30", "21:30"])),
      happyHours: [{ days: [1, 2, 3, 4], start: "15:00", end: "18:00" }],
      deals: ["food"], dealText: "Deals on lettuce wraps & Brussels sprouts · EmoryCard: free drink or appetizer with a dine-in entrée",
      hhStatus: "reported", sources: [{ label: "Yelp listing", url: "https://www.yelp.com/biz/salaryman-toco-hills-atlanta" }, { label: "EmoryCard discounts", url: "https://www.onecard.emory.edu/emorycard/use-card/eagle-discounts.html" }] },

    // ── Emory Village / North Decatur ─────────────────────────────
    { id: "double-zero", name: "Double Zero", neighborhood: "Emory / Druid Hills",
      address: "1577 N Decatur Rd NE (Emory Village)", lat: 33.78798, lng: -84.32617, price: 2, type: "Restaurant",
      website: "https://www.doublezeroatl.com/", zip: "30307",
      cuisine: ["Italian", "Pizza"], vibes: ["Date night", "Games", "Groups"], outdoor: [],
      hours: days({ 1: ["17:00", "21:00"], 2: ["17:00", "21:00"], 3: ["17:00", "21:00"], 4: ["17:00", "21:00"], 5: ["17:00", "22:00"], 6: ["17:00", "22:00"] }),
      happyHours: [{ days: [1, 2, 3, 4, 5, 6], start: "17:00", end: "18:00", note: "Aperitivo hour" }, { days: [1], start: "17:00", end: "21:00", note: "Half-off bottles of wine" }],
      deals: ["cocktails", "beer", "wine", "food"], dealText: "$9 Negronis · $5 Peronis · small plates & pastas · Mondays: half-off wine bottles 5–9PM",
      hhStatus: "confirmed", sources: [{ label: "Instagram @doublezeroatl (Sep 30, 2026)", url: "https://www.instagram.com/doublezeroatl/" }, { label: "doublezeroatl.com (hours)", url: "https://www.doublezeroatl.com/" }] },

    { id: "poboy-shop", name: "The Po'Boy Shop & Basement Bar", neighborhood: "North Decatur",
      address: "1369 Clairmont Rd, Decatur", lat: 33.79343, lng: -84.30548, price: 1, type: "Bar",
      website: "https://www.thepoboyshopatl.com/", zip: "30033",
      cuisine: ["Cajun", "Sandwiches"], vibes: ["Late night", "Sports", "Games"], outdoor: [],
      hours: [0, 1, 2, 3, 4, 5, 6].map(() => ["11:00", "02:00"]),
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], allDay: true }],
      deals: ["beer"], dealText: "$6 Big Busch",
      hhStatus: "confirmed", sources: [{ label: "thepoboyshopatl.com", url: "https://www.thepoboyshopatl.com/basementbar" }] },

    // ── Decatur ───────────────────────────────────────────────────
    { id: "kimball-house", name: "Kimball House", neighborhood: "Decatur",
      address: "303 E Howard Ave, Decatur", lat: 33.77154, lng: -84.29236, price: 3, type: "Cocktail bar",
      website: "http://kimball-house.com/", zip: "30030",
      cuisine: ["Seafood"], vibes: ["Date night"], outdoor: [], hours: days({ 0: [["12:00", "15:00"], ["17:00", "00:00"]], 1: ["17:00", "00:00"], 2: ["17:00", "00:00"], 3: ["17:00", "00:00"], 4: ["17:00", "00:00"], 5: ["17:00", "01:00"], 6: ["17:00", "01:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "17:00", end: "19:00", note: "Raw bar happy hour" }],
      deals: ["oysters"], dealText: "About half-price oysters from around the country",
      hhStatus: "reported", sources: [{ label: "AJC (2018)", url: "https://www.ajc.com/events/food--wine/dekalb-spots-with-food-and-drink-specials-you-won-want-miss/9jVhuGwrLixr969EjGibVP/" }] },

    { id: "iberian-pig", name: "The Iberian Pig", neighborhood: "Decatur",
      address: "121 Sycamore St, Decatur", lat: 33.77446, lng: -84.29601, price: 3, type: "Restaurant",
      website: "https://www.iberianpig.com/decatur", zip: "30030",
      cuisine: ["Spanish / Tapas"], vibes: ["Date night"], outdoor: ["Patio"], hours: days({ 0: ["16:00", "22:00"], 1: ["17:00", "22:00"], 2: ["17:00", "22:00"], 3: ["17:00", "22:00"], 4: ["17:00", "22:00"], 5: ["17:00", "23:00"], 6: ["16:00", "23:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "17:00", end: "18:00", note: "Jamón Happy Hour" }],
      deals: ["food", "wine"], dealText: "$5 sangria · $5 red & white wine · Charcuterie & tapas specials",
      hhStatus: "confirmed", sources: [{ label: "iberianpig.com", url: "https://www.iberianpig.com/decatur" }] },

    { id: "la-chiquiada", name: "La Chiquiada", neighborhood: "Decatur",
      address: "110 W Trinity Pl, Decatur", lat: 33.77331, lng: -84.29699, price: 1, type: "Restaurant",
      website: "https://lachiquiada.com/", zip: "30030",
      cuisine: ["Mexican / Tacos"], vibes: ["Groups"], outdoor: [], hours: days({ 0: ["09:00", "15:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["11:00", "22:00"], 6: ["09:00", "23:00"] }),
      happyHours: [{ days: [2, 3, 4, 5, 6], start: "16:00", end: "18:00" }],
      deals: ["cocktails", "beer", "wine", "food"], dealText: "Two street tacos $7 · $8 margaritas & classic cocktails · $5 drafts · $6 wine · nachos, wings & chip trio $11–12 · bar & patio only",
      hhStatus: "confirmed", sources: [{ label: "La Chiquiada happy hour menu", url: "https://lachiquiada.com/" }, S.inf] },

    { id: "leilas", name: "Leila's Bar", neighborhood: "Decatur",
      address: "116 Clairemont Ave, Decatur", lat: 33.77614, lng: -84.29694, price: 2, type: "Cocktail bar",
      zip: "30030",
      cuisine: [], vibes: ["Cozy", "Date night"], outdoor: [],
      hours: days({ 1: ["16:00", "22:00"], 2: ["16:00", "22:00"], 3: ["16:00", "22:00"], 4: ["16:00", "22:00"], 5: ["16:00", "22:00"], 6: ["16:00", "22:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "17:00", end: "20:00" }],
      deals: [], dealText: "Weekday happy hour (deals not listed)",
      hhStatus: "reported", sources: [{ label: "Yelp listing", url: "https://www.yelp.com/biz/leila-s-bar-decatur" }] },

    { id: "thinking-man", name: "Thinking Man Tavern", neighborhood: "Decatur",
      address: "537 W Howard Ave, Decatur", lat: 33.76787, lng: -84.30458, price: 1, type: "Pub",
      website: "https://www.thinkingmantavern.com/", zip: "30030",
      cuisine: ["Bar food"], vibes: ["Late night", "Cozy"], outdoor: ["Patio"], hours: days({ 0: ["11:30", "02:00"], 1: ["16:00", "24:00"], 2: ["11:30", "24:00"], 3: ["11:30", "24:00"], 4: ["11:30", "24:00"], 5: ["11:30", "01:00"], 6: ["11:30", "01:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "15:00", end: "18:00" }, { days: [0, 1, 2, 3, 4, 5, 6], start: "22:00", end: "close", note: "Late-night happy hour" }],
      deals: ["beer", "cocktails"], dealText: "$2.50 PBRs · $4 well drinks · $5 Paddy's Irish whiskey · $2 Koji sakes",
      hhStatus: "confirmed", sources: [{ label: "thinkingmantavern.com (happy hour flyer)", url: "https://www.thinkingmantavern.com/" }] },

    { id: "parkers-on-ponce", name: "Parker's on Ponce", neighborhood: "Decatur",
      address: "116 E Ponce de Leon Ave, Decatur", lat: 33.77573, lng: -84.29588, price: 3, type: "Restaurant",
      website: "https://parkersonponce.com/", zip: "30030",
      cuisine: ["Steakhouse", "Seafood"], vibes: ["Date night"], outdoor: [], hours: null,
      happyHours: [
        { days: [1], start: "17:00", end: "22:00", note: "Half-price Parker's Martini & Manhattan" },
        { days: [3], start: "17:00", end: "22:00", note: "50% off bottles of wine" },
        { days: [4], start: "17:00", end: "22:00", note: "Half-price specialty cocktails" },
      ],
      deals: ["cocktails", "wine"], dealText: "Mon: half-price martinis & Manhattans · Wed: 50% off wine bottles · Thu: half-price specialty cocktails · Fri: featured whiskeys (not for parties of 6+)",
      hhStatus: "confirmed", sources: [{ label: "parkersonponce.com (specials)", url: "https://parkersonponce.com/decatur-dekalb-parkers-on-ponce-happy-hours-specials" }] },

    { id: "brick-store", name: "Brick Store Pub", neighborhood: "Decatur",
      address: "125 E Court Sq, Decatur", lat: 33.77514, lng: -84.29581, price: 2, type: "Pub",
      website: "https://www.brickstorepub.com/", zip: "30030",
      cuisine: ["Bar food"], vibes: ["Cozy", "Groups"], outdoor: [],
      hours: days({ 0: ["11:30", "23:30"], 1: ["16:30", "23:30"], 2: ["11:30", "23:30"], 3: ["11:30", "23:30"], 4: ["11:30", "23:30"], 5: ["11:30", "00:30"], 6: ["11:30", "00:30"] }),
      happyHours: [], deals: ["beer"], dealText: "Legendary beer list (30 drafts + Belgian bar); happy hour times not published",
      hhStatus: "unknown", sources: [{ label: "brickstorepub.com", url: "https://www.brickstorepub.com/" }] },

    { id: "leons", name: "Leon's Full Service", neighborhood: "Decatur",
      address: "131 E Ponce de Leon Ave, Decatur", lat: 33.77538, lng: -84.29512, price: 2, type: "Bar",
      website: "https://www.leonsfullservice.com/", zip: "30030",
      cuisine: ["American"], vibes: ["Groups", "Late night"], outdoor: ["Patio"],
      hours: days({ 0: ["11:30", "01:00"], 1: ["17:00", "01:00"], 2: ["11:30", "01:00"], 3: ["11:30", "01:00"], 4: ["11:30", "01:00"], 5: ["11:30", "02:00"], 6: ["11:30", "02:00"] }),
      happyHours: [], deals: [], dealText: "Popular happy hour spot in an old service station; times not published",
      hhStatus: "unknown", sources: [{ label: "leonsfullservice.com", url: "https://www.leonsfullservice.com/" }] },

    // ── Edgewood Ave ──────────────────────────────────────────────
    { id: "marcus", name: "Marcus Bar & Grille", neighborhood: "Edgewood",
      address: "525 Edgewood Ave SE", lat: 33.75408, lng: -84.37032, price: 2, type: "Restaurant",
      website: "https://www.marcusbarandgrille.com/", zip: "30312",
      cuisine: ["Southern"], vibes: ["Date night", "Groups"], outdoor: ["Patio"],
      hours: days({ 0: ["10:30", "22:00"], 2: ["17:00", "22:00"], 3: ["17:00", "22:00"], 4: ["17:00", "22:00"], 5: ["17:00", "23:00"], 6: ["10:30", "23:00"] }),
      happyHours: [{ days: [2, 3, 4, 5], start: "16:00", end: "18:00", note: "At the bar, high-tops & patio" }],
      deals: ["cocktails", "food"], dealText: "$10 cocktails · Brisket sliders, wings & jollof arancini $8–14",
      hhStatus: "confirmed", sources: [{ label: "marcusbarandgrille.com", url: "https://www.marcusbarandgrille.com/location/marcus-bar-and-grille/" }] },

    { id: "miss-conduck", name: "Miss Conduck", neighborhood: "Edgewood",
      address: "357 Edgewood Ave SE", lat: 33.75431, lng: -84.37626, price: 2, type: "Restaurant",
      website: "https://missconduck.com/",
      zip: "30312",
      cuisine: ["Caribbean"], vibes: ["Groups", "Late night"], outdoor: [], hours: null,
      happyHours: [{ days: [0, 1, 2, 3, 4, 5, 6], start: "16:00", end: "19:00" }],
      deals: ["cocktails", "food", "beer"], dealText: "$7 cocktails · $9 jerk chicken egg rolls · $22 jerk burger & beer combo",
      hhStatus: "reported", sources: [{ label: "Yelp listing", url: "https://www.yelp.com/biz/miss-conduck-atlanta" }] },

    { id: "happy-hour-atl", name: "Happy Hour ATL", neighborhood: "Edgewood",
      address: "421 Edgewood Ave SE", lat: 33.75427, lng: -84.37358, price: 1, type: "Sports bar",
      zip: "30312",
      cuisine: [], vibes: ["Sports", "Late night"], outdoor: [], hours: null,
      happyHours: [
        { days: [2], start: "17:00", end: "22:00", note: "Tito's + Tacos Tuesday" },
        { days: [3], allDay: true, note: "Wishful Wednesdays: $1 wings, $2 tacos, $20 pitchers" },
        { days: [4], allDay: true, note: "Football night: $1 wings, $5 shots" },
        { days: [0], allDay: true, note: "NFL Sunday: $1 wings, $5 shots" },
      ],
      deals: ["food", "cocktails"], dealText: "Tue 5–10PM: $2 tacos, $10 nachos, $3 Tito's shots, $5 margs & lemon drops, $15 hookahs · Wed: $1 wings / $2 tacos + $20 pitchers · Thu & Sun football: $1 wings, $5 shots, 2-for-$25 pasta",
      hhStatus: "confirmed", sources: [{ label: "Instagram @happyhour.atl (Sep–Oct 2026)", url: "https://www.instagram.com/happyhour.atl/" }] },

    // ── Buckhead ──────────────────────────────────────────────────
    { id: "roshambo", name: "Roshambo", neighborhood: "Buckhead",
      address: "2355 Peachtree Rd NE (Peachtree Battle)", lat: 33.81919, lng: -84.38845, price: 2, type: "Restaurant",
      website: "https://roshamboatl.com/", zip: "30305",
      cuisine: ["American", "Seafood"], vibes: ["Date night", "Groups"], outdoor: [],
      hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 0 || d === 6 ? ["10:00", "21:00"] : ["16:00", "21:00"])),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "18:00" }, { days: [6, 0], start: "14:00", end: "17:00" }],
      deals: ["oysters", "cocktails", "wine", "beer"], dealText: "6 raw oysters $12 · 6 broiled $15 · $10 classic cocktails & wine · $4 High Life · $9 wings, tots & hummus",
      hhStatus: "confirmed", sources: [{ label: "Roshambo happy hour menu", url: "https://roshamboatl.com/" }] },

    { id: "snap-thai", name: "Snap Thai Fish House", neighborhood: "Buckhead",
      address: "3699 Lenox Rd NE, Ste 5", lat: 33.85130, lng: -84.37169, price: 2, type: "Restaurant",
      website: "https://www.snapthaiatl.com/", zip: "30342",
      cuisine: ["Thai", "Seafood"], vibes: ["Date night"], outdoor: [], hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 0 ? ["11:30", "21:00"] : ["11:30", "22:00"])),
      happyHours: [{ days: WEEKDAYS, start: "15:00", end: "18:00" }],
      deals: ["oysters", "food", "cocktails", "beer", "wine"], dealText: "$1.50 raw oysters · $2 chargrilled · bites from $5 · $10 cocktails · $5 beer · half-price wine bottles",
      hhStatus: "confirmed", sources: [{ label: "snapthaiatl.com", url: "https://www.snapthaiatl.com/" }] },

    { id: "fado", name: "Fadó Irish Pub", neighborhood: "Buckhead",
      address: "273 Buckhead Ave NE", lat: 33.83802, lng: -84.37862, price: 2, type: "Pub",
      website: "https://www.fadoirishpub.com/atlanta/",
      zip: "30305",
      cuisine: ["British", "Bar food"], vibes: ["Sports", "Groups"], outdoor: ["Rooftop"], hours: days({ 0: ["10:00", "21:00"], 1: ["11:30", "23:00"], 2: ["11:30", "23:00"], 3: ["11:30", "23:00"], 4: ["11:30", "23:00"], 5: ["11:30", "24:00"], 6: ["10:00", "01:00"] }),
      happyHours: [{ days: WEEKDAYS, start: "16:00", end: "19:00" }],
      deals: ["food", "wine", "cocktails"], dealText: "$5 fish & chip cup · $5 corned beef rolls & more bites · $7.50–8 wine, old fashioneds & spritzes",
      hhStatus: "reported", sources: [{ label: "Georgia on My Dime", url: "https://georgiaonmydime.com/atlanta-happy-hour/fado-irish-pub-buckhead/" }, { label: "Atly (Sep 2026)", url: "https://www.atly.com/united-states/georgia/atlanta/buckhead/best-happy-hour" }] },

    { id: "iberian-pig-buckhead", name: "The Iberian Pig Buckhead", neighborhood: "Buckhead",
      address: "3150 Roswell Rd NW", lat: 33.84164, lng: -84.37904, price: 3, type: "Restaurant",
      website: "https://www.iberianpig.com/buckhead", zip: "30305",
      cuisine: ["Spanish / Tapas"], vibes: ["Date night"], outdoor: [], hours: [0, 1, 2, 3, 4, 5, 6].map(d => (d === 5 || d === 6 ? ["16:00", "23:00"] : ["17:00", "22:00"])),
      happyHours: [{ days: [1, 2, 3, 4], start: "17:00", end: "18:00", note: "Jamón Happy Hour" }, { days: [5], start: "16:00", end: "18:00", note: "Jamón Happy Hour" }],
      deals: ["food", "wine", "cocktails"], dealText: "$5 sangria · $5 red & white wine · Charcuterie & tapas specials",
      hhStatus: "confirmed", sources: [{ label: "iberianpig.com", url: "https://www.iberianpig.com/buckhead" }] },

    // ── Buckhead sweep (2026-10-05) ──
    { id: "south-city-buckhead", name: "South City Kitchen Buckhead", neighborhood: "Buckhead",
      address: "3350 Peachtree Rd NE, Suite 175", lat: 33.84904, lng: -84.36562, price: 2, type: "Restaurant",
      website: "https://www.southcitykitchen.com/", zip: "30326",
      cuisine: ["Southern"], vibes: ["Date night"], outdoor: ["Patio"], hours: null,
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "16:00", end: "18:00" },
      ],
      deals: ["cocktails", "wine", "beer", "food"], dealText: "$7 cocktails & wine · $5 SweetWater · Fried green tomatoes $8 · Pimento cheese & deviled eggs $7",
      hhStatus: "confirmed", sources: [{ label: "southcitykitchen.com", url: "https://www.southcitykitchen.com/happy-hour-atlanta" }] },
    { id: "gypsy-kitchen", name: "Gypsy Kitchen", neighborhood: "Buckhead",
      address: "3035 Peachtree Rd NE, Suite A209 (Buckhead Village)", lat: 33.83784, lng: -84.38067, price: 3, type: "Restaurant",
      website: "https://gk-atl.com/", zip: "30305",
      cuisine: ["Spanish / Tapas", "Mediterranean"], vibes: ["Date night", "Groups"], outdoor: ["Rooftop"], hours: null,
      happyHours: [
        { days: [0, 1, 2, 3, 4], start: "16:00", end: "18:00", note: "Rooftop" },
      ],
      deals: ["cocktails", "food"], dealText: "Bites from $6: jamón & feta doughnuts, halloumi fries, Basque nachos · $8 cocktails",
      hhStatus: "confirmed", sources: [{ label: "gk-atl.com", url: "https://gk-atl.com/" }] },
    { id: "north-italia-buckhead", name: "North Italia", neighborhood: "Buckhead",
      address: "3393 Peachtree Rd NE (Lenox Square)", lat: 33.84786, lng: -84.36373, price: 2, type: "Restaurant",
      website: "https://www.northitalia.com/locations/atlanta-ga-buckhead/", zip: "30326",
      cuisine: ["Italian", "Pizza"], vibes: ["Groups"], outdoor: ["Patio"], hours: days({ 0: ["10:00", "22:00"], 1: ["11:00", "22:00"], 2: ["11:00", "22:00"], 3: ["11:00", "22:00"], 4: ["11:00", "22:00"], 5: ["11:00", "23:00"], 6: ["10:00", "23:00"] }),
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "15:00", end: "18:00", note: "In the bar" },
      ],
      deals: ["wine", "cocktails", "food"], dealText: "$8 glasses of wine · $30 wine bottles · Pizzas, arancini & meatballs · Garlic-knot sliders",
      hhStatus: "confirmed", sources: [{ label: "northitalia.com", url: "https://www.northitalia.com/locations/atlanta-ga-buckhead/menus/happy-hour-menu/" }] },
    { id: "5church-buckhead", name: "5Church Buckhead", neighborhood: "Buckhead",
      address: "3379 Peachtree Rd NE", lat: 33.84786, lng: -84.36582, price: 3, type: "Restaurant",
      website: "https://buckhead.5church-atlanta.com/", zip: "30326",
      cuisine: ["American", "Seafood"], vibes: ["Date night", "Live music"], outdoor: [], hours: null,
      happyHours: [
        { days: [1, 2, 3, 4, 5], start: "15:00", end: "19:00", note: "Bar only" },
      ],
      deals: ["oysters", "wine", "cocktails", "food"], dealText: "$1 oysters · $7 wines · featured cocktails & shareable plates",
      hhStatus: "confirmed", sources: [{ label: "buckhead.5church-atlanta.com", url: "https://buckhead.5church-atlanta.com/" }] },
    { id: "fogo-buckhead", name: "Fogo de Chão", neighborhood: "Buckhead",
      address: "3101 Piedmont Rd NE", lat: 33.84065, lng: -84.36939, price: 3, type: "Restaurant",
      website: "https://fogodechao.com/location/atlanta/", zip: "30305",
      cuisine: ["Steakhouse", "Latin"], vibes: ["Groups"], outdoor: [], hours: null,
      happyHours: [
        { days: [1, 2, 3, 4], allDay: true, note: "Bar Fogo" },
      ],
      deals: ["beer", "wine", "cocktails"], dealText: "$6 beers · $8 South American wines · $10 Brazilian cocktails · All day Mon–Thu at Bar Fogo",
      hhStatus: "confirmed", sources: [{ label: "fogodechao.com", url: "https://fogodechao.com/location/atlanta/" }] },

    { id: "atlanta-fish-market", name: "Atlanta Fish Market", neighborhood: "Buckhead",
      address: "265 Pharr Rd NE", lat: 33.83669, lng: -84.37880, price: 3, type: "Restaurant",
      website: "https://atlantafishmarket.com/", zip: "30305",
      cuisine: ["Seafood", "Sushi"], vibes: ["Groups"], outdoor: [], hours: days({ 0: ["11:30", "21:00"], 1: ["11:30", "21:00"], 2: ["11:30", "21:00"], 3: ["11:30", "21:00"], 4: ["11:30", "21:00"], 5: ["11:30", "22:00"], 6: ["11:30", "22:00"] }),
      happyHours: [{ days: [1, 2, 3, 4, 5], start: "15:30", end: "18:30" }],
      deals: ["oysters", "beer", "wine", "cocktails", "food"], dealText: "$4 domestic beers · $8 wines & cocktails · East Coast oysters (4 for $10) · $8 sushi rolls · fish tacos & calamari $10–12",
      hhStatus: "confirmed", sources: [{ label: "Atlanta Fish Market happy hour menu (PDF)", url: "https://atlantafishmarket.com/wp-content/uploads/2025/12/AFM-HAPPY-HOUR-12.03.25-1.pdf" }] },
    { id: "southern-gentleman", name: "The Southern Gentleman", neighborhood: "Buckhead",
      address: "3035 Peachtree Rd NE, Suite A208 (Buckhead Village)", lat: 33.83790, lng: -84.38071, price: 3, type: "Restaurant",
      website: "https://www.thesoutherngentlemanatl.com/", zip: "30305",
      cuisine: ["Southern"], vibes: ["Date night"], outdoor: ["Patio"], hours: days({ 0: [["11:00", "15:00"], ["17:00", "21:00"]], 1: [["11:30", "15:00"], ["16:00", "22:00"]], 2: [["11:30", "15:00"], ["16:00", "22:00"]], 3: [["11:30", "15:00"], ["16:00", "22:00"]], 4: [["11:30", "15:00"], ["16:00", "22:00"]], 5: [["11:30", "15:00"], ["16:00", "23:00"]], 6: [["11:00", "15:00"], ["17:00", "23:00"]] }),
      happyHours: [{ days: [1, 2, 3, 4, 5], start: "16:00", end: "18:00" }],
      deals: ["cocktails", "wine", "food"], dealText: "$8 house old fashioned · $9 spritzes · $8 wine · fried okra & hushpuppies $8, pork belly buns & clams $10",
      hhStatus: "confirmed", sources: [{ label: "Southern Gentleman happy hour menu (PDF)", url: "https://www.thesoutherngentlemanatl.com/s/TSG-HappyHour-2025.pdf" }] },

    // ── Emory Point / Druid Hills (Clifton Rd area) ───────────────
    { id: "srithai-emory", name: "SriThai Emory Point", neighborhood: "Emory / Druid Hills",
      address: "1540 Avenue Pl (Emory Point)", lat: 33.80124, lng: -84.32709, price: 2, type: "Restaurant",
      website: "https://srithaikitchen.com/",
      zip: "30329",
      cuisine: ["Thai", "Sushi"], vibes: ["Groups"], outdoor: [], hours: null,
      happyHours: [
        { days: [1, 3], start: "15:00", end: "18:00", note: "$7 apps & cocktails" },
        { days: [1, 3], start: "18:00", end: "21:00", note: "Wine Night" },
        { days: [0, 1, 2], start: "16:00", end: "21:00", note: "$3 Sushi Night" },
        { days: [5], start: "18:00", end: "21:00", note: "Beer Night" },
      ],
      deals: ["cocktails", "wine", "beer", "food"], dealText: "Happy hour Mon & Wed 3–6: $7 apps & cocktails (gyoza, spring rolls, calamari, edamame, Thai shrimp rolls) · $3 Sushi Nights Sun–Tue 4–9: $3 select nigiri, rolls & apps · Wine Night Mon & Wed 6–9: $5 glasses · Beer Night Fri 6–9: $4 beers · dine-in only",
      hhStatus: "confirmed", sources: [{ label: "In-store specials flyer (photo, Sept 2026)", url: "https://srithaikitchen.com/" }, { label: "srithaikitchen.com (Events at Emory)", url: "https://srithaikitchen.com/" }] },

    { id: "general-muir", name: "The General Muir", neighborhood: "Emory / Druid Hills",
      address: "1540 Avenue Pl, Ste B-230 (Emory Point)", lat: 33.80140, lng: -84.32690, price: 2, type: "Restaurant",
      website: "https://www.thegeneralmuir.com/", zip: "30329",
      cuisine: ["American", "Sandwiches", "Brunch"], vibes: ["Cozy", "Groups"], outdoor: [],
      hours: days({ 0: ["08:00", "20:30"], 1: ["08:00", "14:00"], 2: ["08:00", "14:00"], 3: ["08:00", "20:30"], 4: ["08:00", "20:30"], 5: ["08:00", "21:00"], 6: ["08:00", "21:00"] }),
      happyHours: [{ days: [3, 4, 5], start: "15:30", end: "17:30" }],
      deals: ["cocktails"], dealText: "$8 Manhattans · $8 French 75s · $8 vodka martinis · $8 dill palomas",
      hhStatus: "confirmed", sources: [{ label: "In-store table menu (photo, Oct 2026)", url: "https://www.thegeneralmuir.com/" }, { label: "thegeneralmuir.com", url: "https://www.thegeneralmuir.com/" }] },

  ];
  window.VENUES.forEach(v => { v.checked = CHECKED; });

  // Spots with no known happy hour (hhStatus "unknown") stay in this file as a
  // to-research list but aren't shown on the site. Once you confirm one's
  // happy hour, fill in happyHours and change hhStatus to show it.
  window.VENUES = window.VENUES.filter(v => v.hhStatus !== "unknown");
})();
